diff a/Dockerfile b/Dockerfile	(rejected hunks)
@@ -5,7 +5,7 @@ WORKDIR /src/cads-catalogue-api-service
 COPY environment.yml /src/cads-catalogue-api-service/
 
 RUN conda install -c conda-forge gcc python=3.10 \
-    && conda enc update -n base -f environment.yml
+    && conda env update -n base -f environment.yml
 
 COPY . /src/cads-catalogue-api-service
 
