channels:
- conda-forge
- nodefaults
dependencies:
- attrs
- fastapi
- make
- mypy
- pip
- pre-commit
- psycopg2
- pytest
- pytest-cov
- sqlalchemy
- uvicorn
- fastapi
- pip:
  - fastapi-utils
  - stac-fastapi.api
  - stac_fastapi.extensions
  - stac-fastapi.types
