channels:
- conda-forge
- nodefaults
dependencies:
- python>=3.10
- make
- mypy
- myst-parser
- pre-commit
- pip
- pytest
- pytest-cov
- uvicorn
- fastapi
- attrs
- sqlalchemy
- sqlalchemy-stubs
- requests
- pip:
  - fastapi-utils
  - stac_fastapi.api
  - stac_fastapi.extensions
  - stac_fastapi.types
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinxcontrib-apidoc
