channels:
- conda-forge
- nodefaults
dependencies:
- python>=3.10
- attrs
- fastapi
- make
- mypy
- myst-parser
- pip
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- requests
- sphinx
- sphinxcontrib-apidoc
- sqlalchemy
- sqlalchemy-stubs
- uvicorn
- pip:
  - fastapi-utils
  - stac_fastapi.api
  - stac_fastapi.extensions
  - stac_fastapi.types
