name: Build catalogue-api docker image

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main


jobs:
  build_docker_image:
    name: Build docker image
    uses: ecmwf-projects/cads-build-farm/.github/workflows/docker-build.yaml@main
    with:
      dockerfile: 'Catalogue.Dockerfile'
      chart-repo: 'ecmwf/dss-catalogue-chart'
      package-ref: "CADS_CATALOGUE_API_SERVICE_REF"
    secrets: inherit
